[build]
  command = "pnpm run build"
  publish = ".next"  # ou "out", dependendo de como você exporta o Next.js
  environment = { NODE_VERSION = "18" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".netlify/functions"  # Opcional, só se você tiver funções serverless

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true
  conditions = { Role = ["/*"] }

[dev]
  framework = "next"
